apiVersion: v1
kind: Service
metadata:
  name: saleor-dashboard-svc
spec:
  selector:
    app: saleor-dashboard
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-dashboard
spec:
  selector:
    matchLabels:
      app: saleor-dashboard
  template:
    metadata:
      labels:
        app: saleor-dashboard
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
        - name: saleor-dashboard
          image: 127.0.0.1:34494/saleor-dashboard:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80

